services:
  fastapi:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    env_file:
      - .env
    depends_on:
      - mongodb

  #django:
  #  build: ./django_admin
  #  ports:
  #    - "8001:8000"
  #  volumes:
  #    - ./django_admin:/app
  #  env_file:
  #    - .env
  # depends_on:
  #    - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
