services:
  fastapi:
    build:
      context: ./faqbot  # Caminho para a pasta com o Dockerfile
      args:
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - MONGO_URL=${MONGO_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./faqbot:/app
    env_file:
      - ./faqbot/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
