services:
  fastapi:
    build:
      context: ./faqbot
      args:
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - MONGO_URL=${MONGO_URL}
        - ADMIN_INITIAL_USERNAME=${ADMIN_INITIAL_USERNAME}
        - ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./faqbot:/app
      - model_cache:/app/cache
    env_file:
      - ./faqbot/.env
    environment:
      - HF_HOME=/app/cache/huggingface
      - SENTENCE_TRANSFORMERS_HOME=/app/cache/sentence_transformers
      - HF_HUB_CACHE=/app/cache/huggingface/hub
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  model_cache: